version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Server
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_CONNECT=mongodb://mongo:27017/blogMonkey
      - JWT_SECRET=SECRET
    depends_on:
      - mongo

  frontend:
    build: ./Client
    ports:
      - 5173:5173
      
volumes:
  mongo-data:  # This defines the volume